VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsSVProcess"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'Class Module:clsProcess

Private Sub setUpBeforeClass()
    'Dim sv
End Sub

Private Sub Initial_SingleView()

End Sub

Private Sub TearDownAfterMethod()

End Sub

Private Sub TearDownAfterClass()

End Sub
